### ISSUE TITLE
The 32-bit libdoorstop.so does not work with the itch.io Linux version

### ISSUE THREAD

**Issue by hanophora** [BrandenEK/AShortHike.ModdingTools#4]
I've got the game through itch.io, which ships a 64-bit version

```
$ file AShortHike.x86_64
AShortHike.x86_64: ELF 64-bit LSB executable, x86-64, version 1 (SYSV), dynamically linked, interpreter /lib64/ld-linux-x86-64.so.2, for GNU/Linux 2.6.32, BuildID[sha1]=2a1da7a4ffbc16bad3cab634551563522905febf, stripped
```

As a result, the provided libdoorstop.so doesn't load, and the game runs as vanilla.
```
$ ./run_bepinex.sh
/home/me/some/dirs/a-short-hike/AShortHike.x86_64
ERROR: ld.so: object 'libdoorstop.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
```

I've fixed it by downloading the 64-bit version of the library [from the BepInEx repo](https://github.com/BepInEx/BepInEx/releases/download/v6.0.0-pre.2/BepInEx-Unity.Mono-linux-x64-6.0.0-pre.2.zip).

The zip file should probably ship both versions, and the script should check for the executable and load the correct one.

**Comment by ChargedNeon** [comment]
This was working in the previous release of the modding tools. `libdoorstop.so` was included in a separate folder (`doorstop_libs`), and `run_bepinex.sh` would detect the required architecture and include the correct `libdoorstop.so` version.

**Comment by BrandenEK** [comment]
Should be fixed now with the new Steam/Itch.io versions

**Comment by TheCakemeister** [comment]
Having just tried launching the steam version, this is still an issue

**Comment by BrandenEK** [comment]
@TheCakemeister what exactly is your issue?  This was only a fix for the itch.io version, the steam version is unchanged.

**Comment by TheCakemeister** [comment]
The libdoorstop included was the 32-bit version, which wasn't working with the 64-bit version (my) Steam was running.
